### PR TITLE
port to ESM modules (gnome 45)

### PR DESCRIPTION
**Pull request by ChrisLauinger77**
gnome 45 - ESM modules. it will only work on gnome 45 and newer.
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#shell-version
When the extension only supports GNOME 44 and later the compiled schemas should not be included any more.

extension is ported for now and loads
prefs is WIP

### CODE REVIEW

**Comment by ChrisLauinger77** [comment]
@cliffniff I would be interested to continue development.
Wanna add me as mainteiner ?

**Comment by ChrisLauinger77** [comment]
some preview - prefs dialog - work in progress

Bildschirmfoto vom 2023-08-24 17-13-22

**Comment by ChrisLauinger77** [comment]
Page2
Bildschirmfoto vom 2023-08-25 15-13-06
Page3
Bildschirmfoto vom 2023-08-25 15-13-17

**Comment by cliffniff** [comment]
@ChrisLauinger77  sorry for not replying earlier. I can add you as a maintainer. I have some time in my hands in the coming months so I will be able to contribute as well.

**Comment by ChrisLauinger77** [comment]
@cliffniff OK cool thx.

**Comment by ChrisLauinger77** [comment]
@cliffniff will you upload it to https://extensions.gnome.org/extension/4470/media-controls/ ?

**Comment by cliffniff** [comment]
I will upload it. What system did you test it on. I tried installing it on fedora 39 beta, could not get it to work.

**Comment by ChrisLauinger77** [comment]
I have it running in a VM GNOME OS nightly.

**Comment by ChrisLauinger77** [comment]
@cliffniff If there is any finding from the review EGO - please tell me. Maybe create an issue which I can work on ?

**Comment by cliffniff** [comment]
@ChrisLauinger77 The review is still pending..

**Comment by ChrisLauinger77** [comment]
@cliffniff Wow - usually they are really really fast. Anyways.
I did dome work in gnome44 and main. Fixed some bugs and splitted the prefs page4 into 2.

**Comment by cliffniff** [comment]
@ChrisLauinger77 That's great. I can also start contributing from tomorrow onwards, since I have some spare time. It's been two days since I submitted for review, I guess they have a lot of extensions to review since Gnome 45 release.

**Comment by ChrisLauinger77** [comment]
@cliffniff Might be they are busy. I did the 4 I maintain during the beta. But a lot of people waited until release ...

**Pull request merged**
